title: Creepy's Corner 
description: A place to view Creepy's ReShade guides.
show_downloads: false
theme: jekyll-theme-midnight
url: "https://creepysasquatch.github.io"
github:
  username: CreepySasquatch
markdown: CommonMarkGhPages